### ISSUE TITLE
INotifyPropertyChanged is still projected to Microsoft.UI.Xaml.Data.INotifyPropertyChanged

### ISSUE THREAD

**Issue by driver1998** [dongle-the-gadget/CsWinRTProjectionForWindows#1]
Trying to debug why data binding does not work properly, found out that the custom WinRT.Runtime still maps to Microsoft.UI.Xaml.Data.INotifyPropertyChanged (`90B17601-B065-586E-83D9-9ADC3A695284`) instead of Windows.UI.Xaml.Data.INotifyPropertyChanged (`cf75d69c-f2f4-486b-b302-bb4c09baebfa`).

![image](https://user-images.githubusercontent.com/22699485/230877874-c33b2294-8555-4deb-bd3c-7ac20e306138.png)

**Comment by dongle-the-gadget** [comment]
Should be fixed on my custom C#/WinRT projection now. I'll publish an update later.

**Comment by driver1998** [comment]
Might want to check INotifyCollectionChanged as well, I updated these in my own fork:
https://github.com/driver1998/CsWinRT/commit/6056d397a22a773b46f78e26f71af460b53c2f65

**Comment by dongle-the-gadget** [comment]
Thanks! Updated.

**Comment by dongle-the-gadget** [comment]
The update (10.0.19041.4) should be live within a few minutes on NuGet.

**Comment by dongle-the-gadget** [comment]
It's live now.

**Comment by driver1998** [comment]
Thanks! works just fine.

![image](https://user-images.githubusercontent.com/22699485/231150056-b769f4ef-f124-45a5-836c-d47eb213ae2a.png)
